config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'file_processing#new'
  resources :home do
    collection do
      get 'convert'
      get 'list'
      get 'image'
    end
  end
  resources :file_processing, only:[ :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  require 'rmagick'
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :allow_facebook_iframe
  
  private

  def allow_facebook_iframe
    response.headers['X-Frame-Options'] = 'ALLOWALL'
  end
end

app/controllers/file_processing_controller.rb
class FileProcessingController < ApplicationController

  def new
  end

  def create
    binding.pry
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 # require 'pdfcrowd'
 require 'rtesseract'
  def index
    @image = Image.new
  end

  def create
    params[:image].each do |img|
      @image = Image.new(image: img)
      @image.save
      convert(@image)
    end
    @images = Image.all
      respond_to do |format|
        format.js
    end
  end

  def convert(file)
    list = ["contact", "energyonline", "flick", "genesis", "meridian","trust"]
    type = file.image.content_type
    text = []
    if type == "application/pdf"
      reader = PDF::Reader.new(file.image.path)
      reader.pages.each do |page|
        text << page.text
      end
      list.each do |l|
        if text[0].include? l
          send(l+"_processing", text)
        end
      end
    else
      # process_image
      # image = RTesseract.new(Image.last.image.path, :lang => "eng")
      # text = image.to_s
      # store_text

    end
    @images = Image.all
  end

  def list
    @images = Image.all
  end

  def image
  end

  private

  def image_params
     params.require(:image).permit(:image)
  end

  def pdf_pages
    reader = PDF::Reader.new(Image.last.image.path)
    pages_arr = []
    reader.pages.each{|page| pages_arr = page.text.split("\n")}
    pages_arr
  end

  def get_start_date (the_str)
    start_date = the_str[0].split("from ")[1].delete(" to")
  end

  def get_end_date (pages_arr)
    the_line = find_text(pages_arr,"from")
    the_index = pages_arr.index(the_line)
    end_date = pages_arr[1]
  end

  def find_text(the_arr, the_text)
    the_arr.select{|item| item.downcase.include? the_text }
  end

  def contact_processing(text)
    pages_arr = pdf_pages
    name = "Contact Energy Residential Electricity"
    icp = find_text(pages_arr,"icp")[0].split(" ")[14]
    total_cost_line = find_text(pages_arr,"if paid after")[0].split(" ").last
    start_date = get_start_date(find_text(pages_arr,"from"))
    end_date = get_end_date(pages_arr)
    Image.last.update(name: name, icp: icp, total: total_cost_line, start_date: start_date, end_date: end_date)
    puts "**************\n"
    puts "end_date: #{end_date}"
    puts "**************\n"
  end

  def energyonline_processing(text)
    pages_arr = pdf_pages
    name = "Energy Online"
    icp = find_text(pages_arr," icp")[0].split(" ")[2]
    total_cost_line = pages_arr.last.split( " GST ").last.delete("(").delete(")")
    start_date = get_start_date(find_text(pages_arr," from"))[0..7]
    end_date = get_start_date(find_text(pages_arr," from"))[8..15]
    Image.last.update(name: name, icp: icp, total: total_cost_line, start_date: start_date, end_date: end_date)
  end

  def flick_processing(text)

  end

  def genesis_processing(text)

  end

  def meridian_processing(text)

  end

  def trust_processing(text)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_processing_helper.rb
module FileProcessingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/file_processing/new.html.erb
<!--  <%#= form_for(@image, remote: true, url: home_index_path, method: 'post') do |f| %>
  <%#= f.file_field :image %>
      <%#= f.submit %>
  <%# end %>
<%#= link_to 'Convert', convert_home_index_path %> -->

<div class="col-md-12 bg-otr p-0">
            <div class="col-md-12 svg-sec float-left">
            <div class="col-md-12 p-0">
                  <nav class="navbar navbar-dark bg-transparent">
                    <div class="container contr-otr">
                        <a class="navbar-brand" href="#"><img src="/assets/logo.png"></a>
                       <ul class="navbar-nav ml-auto log-sec d-flex">
                          <li class="nav-item active">
                            <a class="nav-link" href="#">Login</a>
                          </li>
                           <li class="nav-item active">
                            <a class="nav-link" href="<%= image_home_index_path%>">Signup</a>
                          </li>
                      </ul>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse" id="navbarsExample01">
                        <ul class="navbar-nav mr-auto">
                          <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                              <a class="dropdown-item" href="#">Action</a>
                              <a class="dropdown-item" href="#">Another action</a>
                              <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                          </li>
                        </ul>
                        <form class="form-inline my-2 my-md-0">
                          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                        </form>
                      </div>
                      </div>
                    </nav>
                </div>
                <div class="col-md-12 p-0 file-upload-section">
                    <div class="container contr-otr">
                        <div class="otr-upload">
                          <div class="upload-sec">
                            <h3 class="text-center">File sharing and storage</h3>
                            <h4 class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever</h4>
                              <div class="col-md-12 float-left">
                                <div class="container contr-otr-sec">
                                    <div class="col-md-12 upload-inner">
                                      <div class="col-md-12 detail-otr">
                                        <%= form_tag("/file_processing", method: 'post', remote: true ) do %>
                                        <div class="fil-otr upld-fl">
                                          <%= file_field_tag 'the_file',id: 'files', multiple: true %>
                                          <div class="cst-otr"><label for="files" class="custom-file-upload">
                                                <i class="fa fa-cloud-upload"></i> Select Files to Upload
                                            </label>
                                          </div>
                                          <div class="fl-out">
                                            <div >
                                              <%= submit_tag 'Upload' , class: 'upload-btn'%>
                                            </div>
                                          </div>
                                        </div>
                                      <% end %>
                                    </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
                 <div class="col-md-12 section-bt float-left">
                    <h3 class="text-center">How To Work</h3>
                    <%#= link_to 'Convert', convert_home_index_path %>
                    <%#= link_to 'List', list_home_index_path%>
                            <h4 class="text-center">Lorem Ipsum has been the industry's standard dummy text ever</h4>
                </div>
        </div>



          </div><script>
  $(document).ready(function() {
  if (window.File && window.FileList && window.FileReader) {
    $("#files").on("change", function(e) {
       //alert();
        //var get_length2 = $this.closest('.fl-out').find('.pip').length;
        //alert( get_length2 );
      var files = e.target.files,
        filesLength = files.length;
      for (var i = 0; i < filesLength; i++) {
        var f = files[i]
        var fileReader = new FileReader();
        fileReader.onload = (function(e) {
          var file = e.target;
          $("<div class=\"pip\">" + "<div class=\"imgout\">" +
            "<img class=\"imageThumb\" src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" + "</div>" +
            "<span class=\"remove\" onclick='renoveEl(this)'>Remove</span>" +
            "</div>").appendTo(".fl-out");
          var get_length2 = $('.fl-out').find('.pip').length;
          //renoveEl();
          if( filesLength > 0 ){
            $('.upload-btn').show();
          }
          //$('.upload-btn2').show();
        });
        fileReader.readAsDataURL(f);
      }
       // $(document).on('click', '.pip .remove', function(e){
       //      $this = $(this);
       //      //$this.closest('.fl-out').html('');
       //      $this.closest(".pip").remove();
       //      var get_length = $this.closest('.fl-out').find('.pip').length;
       //      if( get_length == 0 ){
       //         alert(get_length);
       //      }
       //      else{
       //          alert('Hi.');
       //      }
       //  });
    });
  } else {
    alert("Your browser doesn't support to File API")
  }
});

function renoveEl(e){
//$(".remove").click(function(){
                $this = $(e);
                var get_length = $this.closest('.fl-out').find('.pip').length;
                //$('.upload-btn').show();
                //alert('first' + get_length);
                if( get_length > 1 ){
                    $this.closest(".pip").remove();
                    $('.upload-btn').show();
                }
                else{
                    alert(get_length);
                    $this.closest(".pip").remove();
                    $('.upload-btn').hide();
                    //$this.closest('.fl-out').html('');
                }
              //});
            }

</script>

app/views/home/convert.html.erb
<table>
    <td>Name</td>
  <td>ICP</td>
  <td>Start Date</td>
  <td>End Date</td>
  <td>Total</td>
<% @images.each do |img|%>
<tr>
  <td><%= img.name%></td>
  <td><%= img.icp%></td>
  <td><%= img.start_date%></td>
  <td><%= img.end_date%></td>
  <td><%= img.total%></td>
</tr>
<% end %>
</table>

app/views/home/create.js.erb
window.location.replace("<%= list_home_index_path(@images) %>");

app/views/home/image.html.erb
  <div id="video-container">
    <video autoplay></video>
    <input type="file" accept="image/*" capture="camera" />
  </div>
<script >
var errorCallback = function(e) {
    console.log('Reeeejected!', e);
  };

  // Not showing vendor prefixes.
  navigator.getUserMedia({video: true, audio: true}, function(localMediaStream) {
    var video = document.querySelector('video');
    video.src = window.URL.createObjectURL(localMediaStream);

    // Note: onloadedmetadata doesn't fire in Chrome when using it with getUserMedia.
    // See crbug.com/110938.
    video.onloadedmetadata = function(e) {
      // Ready to go. Do some stuff.
    };
  }, errorCallback);
</script>

app/views/home/index.html.erb
<!--  <%#= form_for(@image, remote: true, url: home_index_path, method: 'post') do |f| %>
  <%#= f.file_field :image %>
      <%#= f.submit %>
  <%# end %>
<%#= link_to 'Convert', convert_home_index_path %> -->

<div class="col-md-12 bg-otr p-0">
            <div class="col-md-12 svg-sec float-left">
            <div class="col-md-12 p-0">
                  <nav class="navbar navbar-dark bg-transparent">
                    <div class="container contr-otr">
                        <a class="navbar-brand" href="#"><img src="/assets/logo.png"></a>
                       <ul class="navbar-nav ml-auto log-sec d-flex">
                          <li class="nav-item active">
                            <a class="nav-link" href="#">Login</a>
                          </li>
                           <li class="nav-item active">
                            <a class="nav-link" href="<%= image_home_index_path%>">Signup</a>
                          </li>
                      </ul>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse" id="navbarsExample01">
                        <ul class="navbar-nav mr-auto">
                          <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                              <a class="dropdown-item" href="#">Action</a>
                              <a class="dropdown-item" href="#">Another action</a>
                              <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                          </li>
                        </ul>
                        <form class="form-inline my-2 my-md-0">
                          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                        </form>
                      </div>
                      </div>
                    </nav>
                </div>
                <div class="col-md-12 p-0 file-upload-section">
                    <div class="container contr-otr">
                        <div class="otr-upload">
                          <div class="upload-sec">
                            <h3 class="text-center">File sharing and storage</h3>
                            <h4 class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever</h4>
                              <div class="col-md-12 float-left">
                                <div class="container contr-otr-sec">
                                    <div class="col-md-12 upload-inner">
                                      <div class="col-md-12 detail-otr">
                                      <%= form_for(@image, remote: true, url: home_index_path, method: 'post',:html => { :multipart => true}) do |f| %>
                                        <div class="fil-otr upld-fl">
                                          <%= f.file_field :image, id: 'files', multiple: true , name: 'image[]', capture: "camera"%>
                                          <div class="cst-otr"><label for="files" class="custom-file-upload">
                                                <i class="fa fa-cloud-upload"></i> Select Files to Upload
                                            </label>
                                          </div>
                                          <div class="fl-out">
                                            <div >
                                              <%= f.submit  'Upload' , class: 'upload-btn'%>
                                            </div>
                                          </div>
                                        </div>
                                         <% end %>
                                    </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
                 <div class="col-md-12 section-bt float-left">
                    <h3 class="text-center">How To Work</h3>
                    <%#= link_to 'Convert', convert_home_index_path %>
                    <%#= link_to 'List', list_home_index_path%>
                            <h4 class="text-center">Lorem Ipsum has been the industry's standard dummy text ever</h4>
                </div>
        </div>



          </div><script>
  $(document).ready(function() {
  if (window.File && window.FileList && window.FileReader) {
    $("#files").on("change", function(e) {
       //alert();
        //var get_length2 = $this.closest('.fl-out').find('.pip').length;
        //alert( get_length2 );
      var files = e.target.files,
        filesLength = files.length;
      for (var i = 0; i < filesLength; i++) {
        var f = files[i]
        var fileReader = new FileReader();
        fileReader.onload = (function(e) {
          var file = e.target;
          $("<div class=\"pip\">" + "<div class=\"imgout\">" +
            "<img class=\"imageThumb\" src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" + "</div>" +
            "<span class=\"remove\" onclick='renoveEl(this)'>Remove</span>" +
            "</div>").appendTo(".fl-out");
          var get_length2 = $('.fl-out').find('.pip').length;
          //renoveEl();
          if( filesLength > 0 ){
            $('.upload-btn').show();
          }
          //$('.upload-btn2').show();
        });
        fileReader.readAsDataURL(f);
      }
       // $(document).on('click', '.pip .remove', function(e){
       //      $this = $(this);
       //      //$this.closest('.fl-out').html('');
       //      $this.closest(".pip").remove();
       //      var get_length = $this.closest('.fl-out').find('.pip').length;
       //      if( get_length == 0 ){
       //         alert(get_length);
       //      }
       //      else{
       //          alert('Hi.');
       //      }
       //  });
    });
  } else {
    alert("Your browser doesn't support to File API")
  }
});

function renoveEl(e){
//$(".remove").click(function(){
                $this = $(e);
                var get_length = $this.closest('.fl-out').find('.pip').length;
                //$('.upload-btn').show();
                //alert('first' + get_length);
                if( get_length > 1 ){
                    $this.closest(".pip").remove();
                    $('.upload-btn').show();
                }
                else{
                    alert(get_length);
                    $this.closest(".pip").remove();
                    $('.upload-btn').hide();
                    //$this.closest('.fl-out').html('');
                }
              //});
            }

</script>

app/views/home/list.html.erb
<div class="col-md-12 bg-otr p-0">
  <div class="col-md-12 svg-sec float-left">
    <div class="col-md-12 p-0">
                  <nav class="navbar navbar-dark bg-transparent">
                    <div class="container contr-otr">
                        <a class="navbar-brand" href="#"><img src="/assets/logo.png"></a>
                       <ul class="navbar-nav ml-auto log-sec d-flex">
                          <li class="nav-item active">
                            <a class="nav-link" href="#">Login</a>
                          </li>
                           <li class="nav-item active">
                            <a class="nav-link" href="#">Signup</a>
                          </li>
                      </ul>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse" id="navbarsExample01">
                        <ul class="navbar-nav mr-auto">
                          <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                              <a class="dropdown-item" href="#">Action</a>
                              <a class="dropdown-item" href="#">Another action</a>
                              <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                          </li>
                        </ul>
                        <form class="form-inline my-2 my-md-0">
                          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                        </form>
                      </div>
                      </div>
                    </nav>
                </div>
    <div class="container">
      <table>
        <td style="color: white;">Name</td>
      <td style="color: white;">ICP</td>
      <td style="color: white;">Start Date</td>
      <td style="color: white;">End Date</td>
      <td style="color: white;">Total</td>
    <% @images.each do |img|%>
    <tr>
      <td style="color: white;"><%= img.name%></td>
      <td style="color: white;"><%= img.icp%></td>
      <td style="color: white;"><%= img.start_date%></td>
      <td style="color: white;"><%= img.end_date%></td>
      <td style="color: white;"><%= img.total%></td>
    </tr>
    <% end %>
    </table>
    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
    <head>

         <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="format-detection" content="telephone=no">
        <title>Index</title>
        <%= csrf_meta_tags %>
        <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
        <!-- Bootstrap CSS -->
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">

    </head>
    <body>
        <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        <%= yield %>
        <div class="col-md-12 footer">
           Copyright 2018 Power Bill Scraper All Rights Reserved
        </div>
          <%= javascript_include_tag 'power_shop' %>
    </body>
</html>